DROP TABLE IF EXISTS nc_voter_master;
DROP TABLE IF EXISTS nc_voter_history;
DROP TABLE IF EXISTS state_counties;
DROP TABLE IF EXISTS user;

CREATE TABLE state_counties (
    state_name VARCHAR(100),
    state_init VARCHAR(5),
    county_name VARCHAR(50),
    PRIMARY KEY (state_name, state_init, county_name)
);

CREATE TABLE nc_voter_master (
    county_id		         smallint(2),
	county_desc		         varchar(15),
	voter_reg_num	         character(12),
	status_cd		         character(2),
	voter_status_desc	     varchar(25),
	reason_cd		         character(2),
	voter_status_reason_desc varchar(60),
	absent_ind		         character(1),
	name_prefx_cd	         character(4),
	last_name		         character(25),
	first_name		         character(20),
	middle_name		         character(20),
	name_suffix_lbl          character(3),
	res_street_address	     varchar(63),
	res_city_desc	         varchar(60),
	state_cd		         character(2),
	zip_code		         character(9),
	mail_addr1		         varchar(40),
	mail_addr2		         varchar(40),
	mail_addr3		         varchar(40),
	mail_addr4		         varchar(40),
	mail_city		         varchar(30),
	mail_state		         character(2),
	mail_zipcode	         character(9),
	full_phone_number	     varchar(12),
	race_code		         character(3),
	ethnic_code		         character(3),
	party_cd		         character(3),
	gender_code		         varchar(1),
	birth_age		         int(4),
	birth_state		         character(2),
	drivers_lic		         character(1),
	registr_dt		         date(10),
	precinct_abbrv	         character(6),
	precinct_desc	         varchar(60),
	municipality_abbrv	     character(6),
	municipality_desc	     varchar(60),
	ward_abbrv		         character(6),
	ward_desc		         varchar(60),
	cong_dist_abbrv	         character(6),
	super_court_abbrv	     character(6),
	judic_dist_abbrv	     character(6),
	nc_senate_abbrv	         character(6),
	nc_house_abbrv	         character(6),
	county_commiss_abbrv     character(6),
	county_commiss_desc	     varchar(60),
	township_abbrv	         character(6),
	township_desc	         varchar(60),
	school_dist_abbrv	     character(6),
	school_dist_desc	     varchar(60),
	fire_dist_abbrv	         character(6),
	fire_dist_desc	         varchar(60),
	water_dist_abbrv	     character(6),
	water_dist_desc	         varchar(60),
	sewer_dist_abbrv	     character(6),
	sewer_dist_desc	         varchar(60),
	sanit_dist_abbrv	     character(6),
	sanit_dist_desc	         varchar(60),
	rescue_dist_abbrv	     character(6),
	rescue_dist_desc	     varchar(60),
	munic_dist_abbrv	     character(6),
	munic_dist_desc	         varchar(60),
	dist_1_abbrv	         character(6),
	dist_1_desc		         varchar(60),
	dist_2_abbrv	         character(6),
	dist_2_desc		         varchar(60),
	confidential_ind	     character(1),
	birth_year		         character(4),
	ncid 		             character(12),
	vtd_abbrv 		         character(6),
	vtd_desc 		         character(60),
	PRIMARY KEY (ncid)
);

CREATE TABLE nc_voter_history (
    county_id          	    int(4),
	county_desc        	    character(60),
	voter_reg_num      	    character(12),
	election_lbl       	    character(10),
	election_desc      	    character(230),
	voting_method      	    character(10),
	voted_party_cd     	    character(3),
	voted_party_desc   	    character(60),
	pct_label          	    character(6),
	pct_description    	    character(60),
	ncid               	    character(12),
	voted_county_id    	    character(3),
	voted_county_desc  	    character(60),
	vtd_label          	    character(6),
	vtd_description		    character(60)
);

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);
